#!/bin/sh
while read file
do

	fullpath="$(pwd)/$file"
	case "$1" in
	"w")
		cp "$file" ~/.config/wall &&
		feh --bg-fill "$HOME/.config/wall" &
		notify-send -i "$HOME/.config/wall" "Wallpaper changed.";;
	
	"e")
		cp "$file" ~/.config/wall &&
		feh --bg-center "$HOME/.config/wall" &
		notify-send -i "$HOME/.config/wall" "Wallpaper changed.";;
	
	"r")
		cp "$file" ~/.config/wall &&
		feh --bg-max "$HOME/.config/wall" &
		notify-send -i "$HOME/.config/wall" "Wallpaper changed.";;
	"t")
		cp "$file" ~/.config/wall &&
		feh --bg-scale "$HOME/.config/wall" &
		notify-send -i "$HOME/.config/wall" "Wallpaper changed.";;

	"y")
		cp "$file" ~/.config/wall &&
		feh --bg-tile "$HOME/.config/wall" &
		notify-send -i "$HOME/.config/wall" "Wallpaper changed.";;
	"C-n")
		echo -n "$file" | xclip -selection clipboard &&
		notify-send -i "$PWD/$file" "$file copied to clipboard";;

	"C-c")
		convert "$file" /tmp/tmp_sxiv_img.png &&
		xclip -selection clipboard -target image/png /tmp/tmp_sxiv_img.png &&
		notify-send -i /tmp/tmp_sxiv_img.png "Image copied to clipboard";;


	"C-d")
		trash-put "$file" ;;
	
	"C-w")
		cp "$file" ~/.config/wall &&
		wal -i "$fullpath" -a 85  &&
		# source the colors.
		#. "${HOME}/.cache/wal/colors.sh"            &&

		# Set the border colors.
		#bspc config normal_border_color "$color1"   &&
		#bspc config active_border_color "$color2"   &&
		#bspc config focused_border_color "$color15" &&
		#bspc config presel_feedback_color "$color1" &&
		notify-send -i "$HOME/.config/wall" "Wallpaper and theme changed.";;

	esac
done
